export FFMPEG_PATH=ffmpeg;
export OPENSHIFT_PYTHON_IP=127.0.0.1;

# PSQL env vars
export OPENSHIFT_POSTGRESQL_DB_HOST=127.0.0.1;
export OPENSHIFT_POSTGRESQL_DB_PORT=5432;
export OPENSHIFT_POSTGRESQL_DB_USERNAME=ymp3;
export OPENSHIFT_POSTGRESQL_DB_PASSWORD=ymp3;
export POSTGRESQL_DB_NAME=ymp3;

# Dev configs
export PLAYLIST_VIDEOS_LIMIT=5;
export PLAYLIST_LIST_LIMIT=25;

# Run
python app.py;
