export FFMPEG_PATH=ffmpeg;
export OPENSHIFT_PYTHON_IP=0.0.0.0;
# export OPENSHIFT_PYTHON_PORT=80;

# PSQL env vars
export OPENSHIFT_POSTGRESQL_DB_HOST=0.0.0.0;
export OPENSHIFT_POSTGRESQL_DB_PORT=5432;
export OPENSHIFT_POSTGRESQL_DB_USERNAME=ymp3;
export OPENSHIFT_POSTGRESQL_DB_PASSWORD=ymp3;
export POSTGRESQL_DB_NAME=ymp3;

# Dev configs
export PLAYLIST_VIDEOS_LIMIT=40;
# export PLAYLIST_LIST_LIMIT=5;
